#!/usr/bin/env ruby

def format(file)
  split = file.split('/')
  return file unless split.size > 1
  "│  " * (split.size - 2) + "└── " + split.last
end

def list(dir, start: true)
  puts dir if start

  `git ls-tree master "#{dir}" --name-only`.split("\n").sort.each do |line|
    split = line.split('/')
    puts format(line)
    list(line + '/', start: false) if File.directory?(line)
  end
end

list(ARGV.first || '.')
