#!/usr/bin/env ruby

if ENV["GMAIL_USERNAME"].nil? || ENV["GMAIL_PASSWORD"].nil? || ARGV.size != 3
  puts "USAGE: gmail-send TO SUBJECT HTML_FILE"
  puts
  puts "GMAIL_USERNAME and GMAIL_PASSWORD needs to be set"
  exit
end

require 'gmail'

gmail = Gmail.connect(ENV["GMAIL_USERNAME"], ENV["GMAIL_PASSWORD"])

gmail.deliver do
  to ARGV[0]
  subject ARGV[1]

  html_part do
    content_type 'text/html; charset=UTF-8'
    body File.read(ARGV[2])
  end
end
